// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZEVyM9lslPFS8fMv2SuZLqH-1pV4ZC_g',
    appId: '1:100869026547:ios:f03f5c6dfae064994a3d86',
    messagingSenderId: '100869026547',
    projectId: 'fooddeliveryapp-ddb69',
    storageBucket: 'fooddeliveryapp-ddb69.firebasestorage.app',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZEVyM9lslPFS8fMv2SuZLqH-1pV4ZC_g',
    appId: '1:100869026547:ios:f03f5c6dfae064994a3d86',
    messagingSenderId: '100869026547',
    projectId: 'fooddeliveryapp-ddb69',
    storageBucket: 'fooddeliveryapp-ddb69.firebasestorage.app',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLDJVjFcmSrI4OwLDSSD6yDMUJZujcURM',
    appId: '1:100869026547:web:72908aa9b692ce3e4a3d86',
    messagingSenderId: '100869026547',
    projectId: 'fooddeliveryapp-ddb69',
    authDomain: 'fooddeliveryapp-ddb69.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-ddb69.firebasestorage.app',
    measurementId: 'G-4RHGJGZQ8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAvEMuqk1TsqN3kxFYT_Xt0ZlBUrxqSrg',
    appId: '1:100869026547:android:afe057a035fe8f0c4a3d86',
    messagingSenderId: '100869026547',
    projectId: 'fooddeliveryapp-ddb69',
    storageBucket: 'fooddeliveryapp-ddb69.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLDJVjFcmSrI4OwLDSSD6yDMUJZujcURM',
    appId: '1:100869026547:web:5810ebc28e6b68ce4a3d86',
    messagingSenderId: '100869026547',
    projectId: 'fooddeliveryapp-ddb69',
    authDomain: 'fooddeliveryapp-ddb69.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-ddb69.firebasestorage.app',
    measurementId: 'G-5N5R0TNQLX',
  );
}
